/**
 * npm run codelists:sync [-- --check]
 *
 * Extracts the code lists that the official Schematron actually enforces (the literal
 * value lists inside the assert tests) and writes them to src/codelists/generated.ts.
 * Using the Schematron as the source means the library accepts exactly the codes the
 * validator accepts. With --check the script fails when the committed file is stale.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { DOMParser, type Document } from '@xmldom/xmldom';
import type { ArtefactLock } from './lib/artefacts.js';
import { extractCodes } from './lib/codelist-extract.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const schematronDir = `${root}validator/.artefacts/pint-ae/trn-invoice/schematron/`;
const target = `${root}src/codelists/generated.ts`;
const SCH_NS = 'http://purl.oclc.org/dsdl/schematron';

interface ListSpec {
  constant: string;
  file: 'pint' | 'ae';
  rule: string;
  description: string;
}

const LISTS: ListSpec[] = [
  { constant: 'CURRENCY_CODES', file: 'pint', rule: 'ibr-cl-03', description: 'ISO 4217 alpha-3 currency codes' },
  { constant: 'COUNTRY_CODES', file: 'pint', rule: 'ibr-cl-14', description: 'ISO 3166-1 alpha-2 country codes' },
  { constant: 'PAYMENT_MEANS_CODES', file: 'pint', rule: 'ibr-cl-16', description: 'UNCL 4461 payment means codes' },
  { constant: 'ALLOWANCE_REASON_CODES', file: 'pint', rule: 'ibr-cl-19', description: 'UNCL 5189 allowance reason codes (PINT subset)' },
  { constant: 'CHARGE_REASON_CODES', file: 'pint', rule: 'ibr-cl-20', description: 'UNCL 7161 charge reason codes' },
  { constant: 'UNIT_CODES', file: 'pint', rule: 'ibr-cl-23', description: 'UN/ECE Recommendation 20 unit codes with Recommendation 21 extension' },
  { constant: 'ENDPOINT_SCHEME_CODES', file: 'pint', rule: 'ibr-cl-25', description: 'Electronic Address Scheme (EAS) codes' },
  { constant: 'ICD_SCHEME_CODES', file: 'pint', rule: 'ibr-cl-10', description: 'ISO 6523 ICD identifier scheme codes' },
  { constant: 'CREDIT_NOTE_REASON_CODES', file: 'ae', rule: 'ibr-001-ae', description: 'PINT AE reasons for credit note (BTAE-03)' },
  { constant: 'BILLING_FREQUENCY_CODES', file: 'ae', rule: 'ibr-005-ae', description: 'PINT AE frequency of billing codes (BTAE-06)' },
  { constant: 'TAX_CATEGORY_CODES', file: 'ae', rule: 'ibr-139-ae', description: 'PINT AE VAT category codes' },
  { constant: 'REVERSE_CHARGE_GOODS_CODES', file: 'ae', rule: 'ibr-006-ae', description: 'PINT AE goods or services subject to reverse charge (BTAE-09)' },
  { constant: 'EMIRATE_CODES', file: 'ae', rule: 'ibr-128-ae', description: 'Country subdivision codes accepted for AE addresses' },
];

function assertTest(doc: Document, rule: string): string {
  const asserts = doc.getElementsByTagNameNS(SCH_NS, 'assert');
  for (let i = 0; i < asserts.length; i += 1) {
    const node = asserts.item(i);
    if (node?.getAttribute('id') === rule) return node.getAttribute('test') ?? '';
  }
  throw new Error(`Rule ${rule} not found in the Schematron`);
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const lock = JSON.parse(await readFile(`${root}validator/artefacts.lock.json`, 'utf8')) as ArtefactLock;
  const parser = new DOMParser();
  const docs: Record<'pint' | 'ae', Document> = {
    pint: parser.parseFromString(await readFile(`${schematronDir}PINT-UBL-validation-preprocessed.sch`, 'utf8'), 'text/xml'),
    ae: parser.parseFromString(await readFile(`${schematronDir}PINT-jurisdiction-aligned-rules.sch`, 'utf8'), 'text/xml'),
  };

  const lines: string[] = [
    '// Generated by scripts/sync-codelists.ts. Do not edit by hand; run `npm run codelists:sync`.',
    `// Source: PINT AE ${lock.pintAe.specificationVersion} Schematron in ${lock.pintAe.url}`,
    `// Archive SHA-256: ${lock.pintAe.sha256}`,
    '// Each list is copied from the value list inside the named assert test, so the library',
    '// accepts exactly the codes that the official validator accepts.',
    '',
  ];
  for (const spec of LISTS) {
    const codes = extractCodes(assertTest(docs[spec.file], spec.rule));
    const unique = [...new Set(codes)];
    lines.push(`/** ${spec.description}. Rule ${spec.rule}; ${unique.length} codes. */`);
    const chunks: string[] = [];
    let current = '';
    for (const code of unique) {
      if (current.length + code.length + 1 > 90) {
        chunks.push(current.trim());
        current = '';
      }
      current += `${code} `;
    }
    if (current.trim()) chunks.push(current.trim());
    // One space-separated string per list keeps the file compact; the parentheses make
    // sure split() applies to the whole concatenation.
    lines.push(`export const ${spec.constant}: ReadonlySet<string> = new Set(`);
    lines.push('  (');
    lines.push(chunks.map((c) => `    '${c} '`).join(' +\n'));
    lines.push('  )');
    lines.push('    .trim()');
    lines.push("    .split(' '),");
    lines.push(');');
    lines.push('');
  }
  const output = lines.join('\n');

  if (check) {
    const current = await readFile(target, 'utf8').catch(() => '');
    if (current !== output) {
      console.error('src/codelists/generated.ts is out of date. Run `npm run codelists:sync` and commit the result.');
      process.exitCode = 1;
      return;
    }
    console.log('Code lists are up to date.');
    return;
  }
  await writeFile(target, output);
  console.log(`Wrote ${LISTS.length} code lists to src/codelists/generated.ts`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
